reference_image_paths: [$(arg package_path)/images/30_sign.png]
save_path: $(arg package_path)/linemod
test_detector: True
test_image_paths: [$(arg package_path)/images/Homographied_screenshot_10.10.2018.png]
test_threshold: 0.01
